[workspace]
members = [
    "src/lpc54114",
    "src/lpc54114-coproc",
]

[profile.release]
opt-level = "s"
debug = true # Symbols are nice and they don't increase the size on flash
lto = true # Better optimizations
incremental = false
codegen-units = 1 # Better optimizations
